### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Stiropor** [kreatorij/nova-filemanager#1]
- [ ] drag&drop field flickers sometimes
- [ ] notifications can be better
- [ ] sorting of files
- [x] fix filesize
- [ ] create folder when browser is in modal view
- [x] file preview
- [x] uploading to folder uploads in root (sending `///` as `current`)

**Comment by OlegBodyansky** [comment]
![image](https://user-images.githubusercontent.com/14930774/188471035-71e08b4c-ec1c-4b67-8a5d-705985770406.png)

**Comment by letoast** [comment]
@Stiropor could we implement something like this as well?
https://github.com/InfinetyEs/Nova-Filemanager/blob/c6595c29e23cab01be6b7e37a069b13844397c91/src/Http/Services/NormalizeFile.php#L74
